<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Translatable\HasTranslations;

class JoinUs extends Model
{
    use SoftDeletes;
//    provider == restaurant == merchant
    use  HasTranslations;
    public $translatable = ['merchant_name'];
   protected $guarded = [];
    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('ordered');
        });

        if (request()->is('api/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('draft', false);
            });
        }

    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function bank()
    {
        return $this->belongsTo(Bank::class);
    }

    public function merchant_type()
    {
        return $this->belongsTo(MerchantType::class);
    }



//    attributes
    public function getSourceNameAttribute()
    {
        switch ($this->source) {
            case User::ANDROID:
                return api('Android');
            case User::WEB:
                return api('Web');
            case User::DASHBOARD:
                return api('Dashboard');
            default:
                return api('unknown status');
                break;
        }

    }



    public function getActionButtonsAttribute()
    {
        $button = '';
        $button .= '<a href="'.route('manager.join_us.edit', $this->id).'" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
        $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        return $button;
    }
}
