<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class MerchantType extends Model
{

    use HasTranslations;

    public $translatable = ['name'];
    protected $guarded = [];
    protected $table = 'merchant_types';

    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('merchant_types.ordered');
        });

        if (request()->is('api/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('merchant_types.draft', false);
            });
        }

    }


    public function getImageAttribute($value)
    {
        return is_null($value) ? asset('meal_image.png') : asset($value);
    }

    public function merchants()
    {
        return $this->hasMany(Merchant::class);
    }

    public function joinUs()
    {
        return $this->hasMany(JoinUs::class);
    }

    //    scopes
    public function scopeNotDraft($query)
    {
        return $query->where('draft', false);
    }

    public function getActionButtonsAttribute()
    {
        $button = '';
        $button .= '<a href="' . route('manager.merchant_type.edit', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
        $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        return $button;
    }
}
